print("welcome to tip calculator...")
bill=input("How much cost is your bill\n")
split=input("How many splits you want\n")
persent=input("How much persent you want togive\n")
bill_1=float(bill)
split_1=int(split)
persent_1=int(persent)
have_to_pay=(bill_1/split_1)*(persent_1/100)
pay=round(have_to_pay, 2)
print(f"Each of you have to pay {pay}")
